spring:
  profiles:
    active: prod
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dbarchivebook
    username: root
    password: wcy828
  mail:
    host: smtphm.qiye.163.com
    from: xjx@zucc.edu.cn
    port: 465
    username: xjx@zucc.edu.cn
    password: 88018729
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true